name: Build
on:
  pull_request:
    branches: [ main ]
jobs:
  build-storybook:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Build docker image
      run: docker build --tag ui-react-docs --file ./storybook.Dockerfile .
  build-package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    env:
      DOCKER_IMAGE: ui-react-build
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Build docker image
      run: docker build --tag $DOCKER_IMAGE .
    - name: Run linting
      run: |
        docker run --name lint $DOCKER_IMAGE npm run lint -- --output-file lint-results.json --output-file-format annotations
        docker cp lint:/app/lint-results.json ./lint-results.json
    - name: Upload linting results
      uses: kibalabs/github-action-create-annotations@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        json-file-path: ./lint-results.json
        check-name: lint-package
        fail-on-error: false
