name: Build
on:
  pull_request:
    branches:
      - main
      - beta-**
jobs:
  build-docs:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: docs-build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          cache-from: type=gha,scope=docs-app
          cache-to: type=gha,mode=max,scope=docs-app
          tags: ${{ env.DOCKER_IMAGE }}
          file: ./docs.Dockerfile
  build-package:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: package-build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          cache-from: type=gha,scope=package
          cache-to: type=gha,mode=max,scope=package
          tags: ${{ env.DOCKER_IMAGE }}
      - name: Run lint-check
        run: |
          docker run --name lint-check $DOCKER_IMAGE make lint-check-ci
          docker cp lint-check:/app/lint-check-results.json ./lint-check-results.json
      - name: Upload lint results
        uses: kibalabs/github-action-create-annotations@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          json-file-path: ./lint-check-results.json
          check-name: lint-check
          fail-on-error: false
          path-prefix: ./src/
      - name: Run type-check
        run: |
          docker run --name type-check $DOCKER_IMAGE make type-check-ci
          docker cp type-check:/app/type-check-results.json ./type-check-results.json
      - name: Upload type-check results
        uses: kibalabs/github-action-create-annotations@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          json-file-path: ./type-check-results.json
          check-name: type-check
          fail-on-error: false
          path-prefix: ./src/
