name: Build
on:
  pull_request:
    branches: [ master ]
env:
  DOCKER_REPO: docker.pkg.github.com/${{ github.repository }}
  DOCKER_TAG: latest
  DIRECTORY: ./ui-react
jobs:
  build-package:
    name: Build package
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Build docker image
      run: docker build $DIRECTORY
  build-storybook:
    name: Build storybook image
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Build docker image
      run: docker build --file $DIRECTORY/storybook.Dockerfile $DIRECTORY
