name: Build
on:
  pull_request:
    branches: [main]
jobs:
  build-docs:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ui-react-docs
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          cache-from: type=gha,scope=docs-app
          cache-to: type=gha,mode=max,scope=docs-app
          tags: ${{ env.DOCKER_IMAGE }}
          file: ./docs.Dockerfile
  build-package:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ui-react-build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          cache-from: type=gha,scope=package
          cache-to: type=gha,mode=max,scope=package
          tags: ${{ env.DOCKER_IMAGE }}
      - name: Run linting
        run: |
          docker run --name linting $DOCKER_IMAGE npm run lint -- --output-file linting-results.json --output-file-format annotations
          docker cp linting:/app/linting-results.json ./linting-results.json
      - name: Upload linting results
        uses: kibalabs/github-action-create-annotations@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          json-file-path: ./linting-results.json
          check-name: lint-package
          fail-on-error: false
      - name: Run typing
        run: |
          docker run --name typing $DOCKER_IMAGE npm run type-check -- --output-file typing-results.json --output-file-format annotations
          docker cp typing:/app/typing-results.json ./typing-results.json
      - name: Upload typing results
        uses: kibalabs/github-action-create-annotations@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          json-file-path: ./typing-results.json
          check-name: type-package
          fail-on-error: false
