name: Build
on:
  pull_request:
    branches: [ main ]
jobs:
  build-storybook:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Build docker image
      run: docker build --tag ui-react-docs --file ./storybook.Dockerfile .
  build-package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    env:
      DOCKER_IMAGE: ui-react-build
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Build docker image
      run: docker build --tag $DOCKER_IMAGE .
    - name: Run typing
      run: |
        docker run --name typing $DOCKER_IMAGE npm run type-check -- --output-file typing-results.json --output-file-format annotations
        docker cp typing:/app/typing-results.json ./typing-results.json
    - name: Upload typing results
      uses: kibalabs/github-action-create-annotations@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        json-file-path: ./typing-results.json
        check-name: type-package
        fail-on-error: false
