name: Release
on:
  push:
    tags: ["v*"]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-release
  cancel-in-progress: false
jobs:
  deploy-package:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: package
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          cache-from: type=gha,scope=package
          cache-to: type=gha,mode=max,scope=package
          tags: ${{ env.DOCKER_IMAGE }}
      - name: Create .npmrc file
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - name: Publish package to npm
        run: docker run -v $(pwd)/.npmrc:/root/.npmrc $DOCKER_IMAGE make publish
  deploy-docs:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}-docs:latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          cache-from: type=gha,scope=docs-app
          cache-to: type=gha,mode=max,scope=docs-app
          tags: ${{ env.DOCKER_IMAGE }}
          file: ./docs.Dockerfile
  run-docs:
    needs: deploy-docs
    runs-on: ubuntu-latest
    env:
      NAME: ui-react-docs
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}-docs:latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.KIBA_APP_BOX_URL }}
          username: ${{ secrets.KIBA_APP_BOX_USER }}
          key: ${{ secrets.KIBA_APP_BOX_SSH_KEY }}
          port: ${{ secrets.KIBA_APP_BOX_PORT }}
          envs: DOCKER_IMAGE,NAME
          script_stop: true
          script: |
            url="ui-react-docs.kibalabs.com"
            varsFile=~/.${NAME}.vars
            docker pull ${DOCKER_IMAGE}
            docker stop ${NAME} && docker rm ${NAME} || true
            docker run \
                --name ${NAME} \
                --detach \
                --publish-all \
                --restart on-failure \
                --env NAME=${NAME} \
                --env VIRTUAL_HOST=${url} \
                --env LETSENCRYPT_HOST=${url} \
                --env-file ${varsFile} \
                ${DOCKER_IMAGE}
  create-release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
